apiVersion: apps/v1
kind: Deployment
metadata:
  name: tocker-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: tocker-operator
  template:
    metadata:
      labels:
        name: tocker-operator
    spec:
      containers:
        - name: tocker-operator
          image: docker.io/alaypatel07/tocker-operator:v0.0.1
          ports:
          - containerPort: 60000
            name: metrics
          command:
          - tocker-operator
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: OPERATOR_NAME
              value: "tocker-operator"
